name: publish-to-codepush

on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install app center
        run: |
          npm install -g appcenter-cli
      - name: Publish to code push
        run: | 
          appcenter codepush release-react -a masimo-lloyds.design/todocp-android -d Production --token=${{secrets.APP_CENTER_TOKEN}}
         
